### ISSUE TITLE
Support ros2 cli commands

### ISSUE THREAD

**Issue by raghaprasad** [ros2/rmw_dps#14]
Support ros2 node list and ros2 topic list commands. 
This should unlock the subsequent features ros2 topic info and ros2 node info.

**Comment by malsbat** [comment]
Full support will depend on https://github.com/intel/dps-for-iot/issues/101.

**Comment by raghaprasad** [comment]
Hi Todd, 

Do you have an update on this issue?  Is there something that we can help with? 
Reading the comments on the linked issue, I am wondering how inter-process-communication works today? E.g when running the talker and listener nodes (provided as examples in ros2) in separate processes, the publishers and subscribers are discovered correctly.

> A late joining subscriber will receive retained messages only when it links to a node. 

I am not sure if I follow this statement. Can you explain?

**Comment by malsbat** [comment]
Hi @raghaprasad, 

The current state is that I've got the the initial implementation of RMW discovery APIs plumbed in to DPS.  What's needed next is for late joining subscribers to receive the advertisement publication (in-progress in DPS), proper handling of nodes going away, and some additional timer work to refresh the advertisement when the underlying DPS advertisement publication expires.

I can certainly push up the in-progress work if you'd like to take a look.  I'll push up the branch later today.

The examples work because discovery is stubbed out to return true.  There's no need to know e.g. the node names or that the subscribers of a specific topic are up and running: just send a message and if the subscriber is listening it will get it.

By late-joining subscriber I mean a subscriber who subscribes after the publisher has sent the message.  DPS has the concept of a retained message where a late subscriber will get the most recently published message.  Today, when a subscriber explicitly links to a publisher (does a short handshake at the DPS layer), the subscriber will receive the retained message.  If the subscriber does not do this, it will not receive the retained message.  

This matters for discovery as I am using retained messages for the advertisements.  Without fixing this a subscriber will not discover existing publishers, only publishers that start after the subscriber is running.

Let me know if that helps or you need more information.

**Comment by raghaprasad** [comment]
Thanks for the explanation. 

I guess that is why published messages are broadcast (send to every subscriber) instead of a multicast  to only the participating nodes? 

Do you have an estimate of when you are likely to get this done?

**Comment by malsbat** [comment]
Yes, in general, although the DPS APIs are there to provide fine-grained control over multicast and how the nodes are linked together.

I'm travelling later this week so it's a short week for me...off the top of my head maybe end of next week or the week after to be feature complete.

**Comment by raghaprasad** [comment]
Sounds good. Would it make sense at all to have someone from our team help with this task? 
Is is parallelizable in any way? We have a big Manual QA operation that is about to happen next week for D. We wanted to see if we could test rmw_dps as well as a part of the QA push. 

Alternately if we can get incremental fixes that would be super helpful as well. 
E.g can we can tackle the expired nodes and advertisements in subsequent iteration. 

Let us know how we can help.

**Comment by malsbat** [comment]
I just pushed up the in-progress work to the introspection branch.  Feel free to try it out, I've only done minimal testing.  

I'm not sure the rest of the work can be parallelized that much, except possibly to make the work in the branch more robust while https://github.com/intel/dps-for-iot/issues/101 gets fixed.  Incremental work seems more realistic to me.

Regardless, without https://github.com/intel/dps-for-iot/issues/101, any tests where the subscriber expects to discover the publishers and the subscriber is created after the publisher will fail.  The other parts you mention are probably not so critical to getting passing tests and are good candidates for subsequent iterations.

**Comment by GregBurns** [comment]
It does relate to how messages a published but not quite the way you describe it.  DPS supports IP multicast and IP unicast (over UDP or TCP).  Oversimplifying a bit, multicast publications are sent with no knowledge if there are any subscribers for the publication, and sent only once. For unicast publications DPS sets up a bi-directional link that is used to exchange subscription information between the nodes at each end. Publications only get sent out on the links that have subscribers either directly or indirectly interested in receiving the publication. Publications can optionally have a TTL that cause the publication to be temporarily stored (retained) in one or more linked nodes even if there are no subscribers for the publication at the time. If a subscriber joins the network within the TTL period the retained publications are delivered to that subscriber. In the case where the publishing node has no links to other nodes multicast publications, even those with a non-zero TTL, are discarded immediately after being sent. The change in progress will allow a subscriber to multicast a subscription packet to stimulate retransmission of matching multicast publications that have a non-zero TTL.

**Comment by alsora** [comment]
@malsbat That's great, I will test the new branch!

Do you plan to integrate the information about discovered nodes and topics into the publish mechanism?
It would definitely improve the performances since ROS systems are not fully connected, so only a limited subset of nodes has to receive messages from each publisher.

**Comment by GregBurns** [comment]
One of the big advantages of DPS that lends to scalability is that is only sends publications, modulo a statistically small % of false positives, to nodes that have subscribers for the publication.  Obviously this is only applies when there are point-to-point connections between nodes, multicast publications are still received by all nodes ☺ and discarded locally.  With service discovery in place in the RMW layer DPS will automatically manage the establishment of point-to-point connections.

**Comment by malsbat** [comment]
Basic support for ros2 cli commands is in https://github.com/ros2/rmw_dps/tree/introspection.  There is still an issue with detecting when nodes go away that needs to be resolved in DPS.

**Comment by raghaprasad** [comment]
@malsbat Will try it out shortly! Thanks for update.

**Comment by malsbat** [comment]
I've got work-in-progress on this in the rmw_dps introspection and dps-for-iot multicast-sub branches.  The introspection branch will check out the multicast-sub branch for you so just blow away both dps_for_iot_cmake_module and rmw_dps_cpp and rebuild and you'll be good to go.

Functionally I believe it's all there, but it needs some more changes with regards to multicast retransmission schedules and reliability of the advertisement/discovery info.  Please feel free to try it out and give feedback, but expect more changes under the hood.

**Comment by malsbat** [comment]
This is working now.
